import { execFile } from "child_process";
import { promisify } from "util";
import path from "path";
import fs from "fs/promises";

const execFileAsync = promisify(execFile);

const FFMPEG_PATH = process.env.FFMPEG_PATH || "ffmpeg";

interface MergeInput {
  videoPath: string;
  durationSeconds: number;
}

interface MergeResult {
  outputPath: string;
  durationSeconds: number;
}

export async function mergeVideoClips(
  clips: MergeInput[],
  outputDir: string,
): Promise<MergeResult> {
  await fs.mkdir(outputDir, { recursive: true });

  const listFile = path.join(outputDir, "concat.txt");
  const listContent = clips
    .map((c) => `file '${c.videoPath}'`)
    .join("\n");
  await fs.writeFile(listFile, listContent);

  const mergedPath = path.join(outputDir, "merged.mp4");

  await execFileAsync(FFMPEG_PATH, [
    "-f", "concat",
    "-safe", "0",
    "-i", listFile,
    "-c", "copy",
    "-y",
    mergedPath,
  ]);

  await fs.unlink(listFile).catch(() => {});

  const totalDuration = clips.reduce((s, c) => s + c.durationSeconds, 0);

  return {
    outputPath: mergedPath,
    durationSeconds: totalDuration,
  };
}

export async function mixAudioWithVideo(
  videoPath: string,
  audioPath: string,
  outputPath: string,
): Promise<void> {
  await fs.mkdir(path.dirname(outputPath), { recursive: true });

  await execFileAsync(FFMPEG_PATH, [
    "-i", videoPath,
    "-i", audioPath,
    "-c:v", "copy",
    "-c:a", "aac",
    "-shortest",
    "-map", "0:v:0",
    "-map", "1:a:0",
    "-y",
    outputPath,
  ]);
}

const WATERMARK_TEXT = "AI 生成内容";

export async function applyAiWatermark(
  videoPath: string,
  outputPath: string,
): Promise<void> {
  await fs.mkdir(path.dirname(outputPath), { recursive: true });

  const drawtext = [
    "drawtext",
    `text='${WATERMARK_TEXT}'`,
    "fontsize=16",
    "fontcolor=white@0.6",
    "box=1",
    "boxcolor=black@0.3",
    "boxborderw=4",
    "x=w-tw-16",
    "y=h-th-16",
  ].join(":");

  await execFileAsync(FFMPEG_PATH, [
    "-i", videoPath,
    "-vf", drawtext,
    "-c:v", "libx264",
    "-c:a", "copy",
    "-y",
    outputPath,
  ]);
}

const AI_METADATA = {
  label: "AI 生成内容",
  generator: "ai-video-pipeline",
  regulation: "《互联网信息服务深度合成管理规定》第十七条",
};

export async function injectAiMetadata(
  videoPath: string,
  outputPath: string,
): Promise<void> {
  await fs.mkdir(path.dirname(outputPath), { recursive: true });

  await execFileAsync(FFMPEG_PATH, [
    "-i", videoPath,
    "-metadata", `title=${AI_METADATA.label}`,
    "-metadata", `comment=Generated by ${AI_METADATA.generator}`,
    "-metadata", `copyright=${AI_METADATA.regulation}`,
    "-c", "copy",
    "-y",
    outputPath,
  ]);
}

export async function finalizeVideo(
  mergedVideoPath: string,
  audioPath: string,
  projectId: string,
): Promise<string> {
  const tmpDir = `/tmp/ai-pipeline/${projectId}`;
  await fs.mkdir(tmpDir, { recursive: true });

  const mixedPath = path.join(tmpDir, "mixed.mp4");
  const watermarkedPath = path.join(tmpDir, "watermarked.mp4");
  const finalPath = path.join(tmpDir, "final.mp4");

  await mixAudioWithVideo(mergedVideoPath, audioPath, mixedPath);
  await applyAiWatermark(mixedPath, watermarkedPath);
  await injectAiMetadata(watermarkedPath, finalPath);

  return finalPath;
}
